slm:
  host: "{{ target_host }}"

keycloak:
  auth-server-url: "{{ keycloak_config['scheme'] }}://{{ keycloak_config['host'] }}:{{ keycloak_config['port'] }}{{ keycloak_config['http']['relative_path'] }}"

awx:
  url: "{{ awx_config['scheme'] }}://{{ awx_config['host'] }}:{{ awx_config['port'] }}"
  users:
    admin:
      username: {{ awx_config['users']['admin']['username'] }}
      password: {{ awx_config['users']['admin']['password'] }}

consul:
  url: "{{ consul_config['scheme'] }}://{{ consul_config['host'] }}:{{ consul_config['port'] }}"
  master_token: {{ consul_config['tokens']['master'] }}

vault:
  url: "{{ vault_config['scheme'] }}://{{ vault_config['host'] }}:{{ vault_config['port'] }}"
  root_token: {{ vault_config['tokens']['root'] }}

notification-service:
  url: "{{ notification_service_config['scheme'] }}://{{ notification_service_config['host'] }}:{{ notification_service_config['port'] }}"
  database:
    host: {{ notification_service_config['database']['host'] }}
    port: {{ notification_service_config['database']['port'] }}
    schema: {{ notification_service_config['database']['schema'] }}
    username: {{ notification_service_config['database']['username'] }}
    password: {{ notification_service_config['database']['password'] }}
  awx:
    username: {{ notification_service_config['awx']['username'] }}
    password: {{ notification_service_config['awx']['password'] }}

resource-management:
  url: "{{ resource_management_config['scheme'] }}://{{ resource_management_config['host'] }}:{{ resource_management_config['port'] }}"
  database:
    host: {{ resource_management_config['database']['host'] }}
    port: {{ resource_management_config['database']['port'] }}
    schema: {{ resource_management_config['database']['schema'] }}
    username: {{ resource_management_config['database']['username'] }}
    password: {{ resource_management_config['database']['password'] }}
  awx:
    username: {{ resource_management_config['awx']['username'] }}
    password: {{ resource_management_config['awx']['password'] }}
  consul:
    token: {{ resource_management_config['consul']['acl-token'] }}
  vault:
    app-role:
      role-id: {{ resource_management_config['vault']['app-role']['role-id'] }}
      secret-id: {{ resource_management_config['vault']['app-role']['secret-id'] }}

service-management:
  url: "{{ service_management_config['scheme'] }}://{{ service_management_config['host'] }}:{{ service_management_config['port'] }}"
  database:
    host: {{ service_management_config['database']['host'] }}
    port: {{ service_management_config['database']['port'] }}
    schema: {{ service_management_config['database']['schema'] }}
    username: {{ service_management_config['database']['username'] }}
    password: {{ service_management_config['database']['password'] }}
  awx:
    username: {{ service_management_config[ 'awx' ][ 'username' ] }}
    password: {{ service_management_config[ 'awx' ][ 'password' ] }}
  consul:
    token: {{ service_management_config[ 'consul' ][ 'acl-token' ] }}
  vault:
    app-role:
      role-id: {{ service_management_config[ 'vault' ][ 'app-role' ][ 'role-id' ] }}
      secret-id: {{ service_management_config[ 'vault' ][ 'app-role' ][ 'secret-id' ] }}

catalog:
  url: "{{ catalog_service_config['scheme'] }}://{{ catalog_service_config['host'] }}:{{ catalog_service_config['port'] }}"
  database:
    host: {{ catalog_service_config['database']['host'] }}
    port: {{ catalog_service_config['database']['port'] }}
    schema: {{ catalog_service_config['database']['schema'] }}
    username: {{ catalog_service_config['database']['username'] }}
    password: {{ catalog_service_config['database']['password'] }}

monitoring:
  prometheus:
    url: "{{ monitoring_config['prometheus']['scheme'] }}://{{ monitoring_config['prometheus']['host'] }}:{{ monitoring_config['prometheus']['port'] }}"
  service:
    url: "{{ monitoring_config['service']['scheme'] }}://{{ monitoring_config['service']['host'] }}:{{ monitoring_config['service']['port'] }}"
