# Definition of realm: https://www.keycloak.org/docs-api/22.0.1/rest-api/index.html#RealmRepresentation
keycloak_realms:
  - realm: "fabos"
    displayName: ""
    displayNameHtml: ""
    enabled: true
    loginTheme: "fabos"
    accessTokenLifespan: 86400

keycloak_realm: fabos

keycloak_realm_roles:
  - name: ssp-user
    isDefault: true
  - name: slm-admin
    isDefault: false

keycloak_default_user:
  username: fabos
  enabled: true
  credentials:
    - type: password
      value: password
      temporary: false
  realmRoles: [ "ssp-user", "slm-admin" ]
