- set_fact:
    aas_compose: "{{ lookup('template', 'aas.yml') }}"

- name: "Start containers"
  community.docker.docker_compose:
    project_name: eclipse-slm
    definition: "{{ aas_compose | from_yaml}}"

- name: "Store resulting compose file"
  template:
    src: "aas.yml"
    dest: "{{ _store_compose_file }}"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)
