version: '3.9'

services:
  aas-discovery:
    image: "eclipsebasyx/aas-discovery:{{ AAS_BASYX_VERSION }}"
    restart: unless-stopped
    ports:
      - 8084:8081
    networks:
      default:
        aliases:
          - aas-discovery
    environment:
      SERVER_PORT: 8081
      SPRING_APPLICATION_NAME: AAS Discovery Service
      BASYX_AASDISCOVERYSERVICE_NAME: aas-discovery-service
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: aas-database
      SPRING_DATA_MONGODB_DATABASE: aas-discovery
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: "{{ AAS_DATABASE_USERNAME }}"
      SPRING_DATA_MONGODB_PASSWORD: "{{ AAS_DATABASE_PASSWORD }}"
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  aas-registry:
    image: "eclipsebasyx/aas-registry-log-mem:{{ AAS_BASYX_VERSION }}"
    restart: unless-stopped
    ports:
      - 8082:8080
    networks:
      default:
        aliases:
          - aas-registry
    environment:
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      SPRING_DATA_MONGODB_URI: "mongodb://{{ AAS_DATABASE_USERNAME }}:{{ AAS_DATABASE_PASSWORD }}@aas-database:27017"

  submodel-registry:
    image: "eclipsebasyx/submodel-registry-log-mem:{{ AAS_BASYX_VERSION }}"
    restart: unless-stopped
    ports:
      - 8083:8080
    networks:
      default:
        aliases:
          - submodel-registry
    environment:
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      SPRING_DATA_MONGODB_URI: "mongodb://{{ AAS_DATABASE_USERNAME }}:{{ AAS_DATABASE_PASSWORD }}@aas-database:27017"

  aas-environment:
    image: "eclipsebasyx/aas-environment:{{ AAS_BASYX_VERSION }}"
    restart: unless-stopped
    environment:
      SERVER_PORT: 8081
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: aas-database
      SPRING_DATA_MONGODB_DATABASE: aas-environment
      SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: "{{ AAS_DATABASE_USERNAME }}"
      SPRING_DATA_MONGODB_PASSWORD: "{{ AAS_DATABASE_PASSWORD }}"
      MQTT_CLIENTID: AAS-Environment
      MQTT_HOSTNAME: aas-broker
      MQTT_PORT: 1884
      BASYX_AASREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_SUBMODELREPOSITORY_FEATURE_MQTT_ENABLED: "true"
      BASYX_CORS_ALLOWEDORIGINS: "*"
      BASYX_CORS_ALLOWEDMETHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry:8080
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://submodel-registry:8080
      BASYX_EXTERNALURL: http://{{ SLM_HOSTNAME }}:8081
    ports:
      - 8081:8081
    networks:
      default:
        aliases:
          - aas-environment

  aas-web-ui_v2:
    image: "eclipsebasyx/aas-gui:{{ AAS_GUI_VERSION }}"
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      AAS_REGISTRY_PATH: "http://{{ SLM_HOSTNAME }}:8082"
      SUBMODEL_REGISTRY_PATH: "http://{{ SLM_HOSTNAME }}:8083"
      AAS_DISCOVERY_PATH: "http://{{ SLM_HOSTNAME }}:8084"
      AAS_REPO_PATH: "http://{{ SLM_HOSTNAME }}:8081/shells"
      SUBMODEL_REPO_PATH: "http://{{ SLM_HOSTNAME }}:8081/submodels"
      CD_REPO_PATH: "http://{{ SLM_HOSTNAME }}:8081/concept-descriptions"

  aas-database:
    image: mongo:5.0.10
    restart: unless-stopped
    networks:
      default:
        aliases:
          - aas-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: "{{ AAS_DATABASE_USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ AAS_DATABASE_PASSWORD }}"
    volumes:
      - aas_database:/data/db
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5

  aas-broker:
    image: "ghcr.io/eclipse-slm/aas/broker:{{ AAS_BROKER_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "1884:1884"
    networks:
      default:
        aliases:
          - aas-broker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 10s
      timeout: 10s
      retries: 6

  aas-transformer:
    image: "ghcr.io/fabos-ai/aas-transformer/service:{{ AAS_TRANSFORMER_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    depends_on:
      - aas-transformer-database
    ports:
      - "4010:4010"
    networks:
      default:
        aliases:
          - aas-transformer
    environment:
      DATABASE_HOST: aas-transformer-database
      DATABASE_SCHEMA: "{{ AAS_TRANSFORMER_DATABASE_NAME }}"
      DATABASE_USERNAME: "{{ AAS_TRANSFORMER_DATABASE_USER }}"
      DATABASE_PASSWORD: "{{ AAS_TRANSFORMER_DATABASE_PASSWORD }}"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"

  aas-transformer-database:
    image: mariadb:10.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    networks:
      default:
        aliases:
          - aas-transformer-database
    environment:
      MARIADB_USER: "{{ AAS_TRANSFORMER_DATABASE_USER }}"
      MARIADB_PASSWORD: "{{ AAS_TRANSFORMER_DATABASE_PASSWORD }}"
      MARIADB_DATABASE: "{{ AAS_TRANSFORMER_DATABASE_NAME }}"
      MARIADB_ROOT_PASSWORD: "{{ AAS_TRANSFORMER_DATABASE_ROOT_PASSWORD }}"
    volumes:
      - "aas_transformer_database:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  aas-transformer-initializer:
    image: "ghcr.io/fabos-ai/aas-transformer/initializer:{{ AAS_TRANSFORMER_VERSION }}"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"

volumes:
  aas_database:
  aas_transformer_database:
