version: '3'

services:
  keycloak:
    image: "ghcr.io/eclipse-slm/keycloak:{{ KEYCLOAK_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ KEYCLOAK_PORT }}:8080"
    depends_on:
      - keycloak-database
    environment:
      KC_HOSTNAME: "{{ keycloak_config.hostname }}"
      KC_DB_HOST: "{{ keycloak_config.database.host }}"
      KC_DB_URL_HOST: "{{ keycloak_config.database.url_host }}"
      KC_DB_SCHEMA: "{{ keycloak_config.database.schema }}"
      KC_DB_USERNAME: "{{ keycloak_config.database.username }}"
      KC_DB_PASSWORD: "{{ keycloak_config.database.password }}"
      KEYCLOAK_ADMIN: "{{ keycloak_config.admin.username }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_config.admin.password }}"
      KC_HTTP_RELATIVE_PATH: "{{ keycloak_config.http.relative_path }}"
    volumes:
      - keycloak-database_config:/keycloak/database/config
    networks:
      default:
        aliases:
          - 'keycloak'
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/auth" ]

  keycloak-database:
    image: "ghcr.io/eclipse-slm/mariadb:{{ KEYCLOAK_DATABASE_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    volumes:
      - keycloak-database_data:/var/lib/mysql
      - keycloak-database_config:/config
    ports:
      - "4406:3306"
    networks:
      default:
        aliases:
          - keycloak-database
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

volumes:
  keycloak-database_data:
  keycloak-database_config:
