version: '3'

services:

  ui:
    image: "ghcr.io/eclipse-slm/slm/ui:{{ SLM_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ UI_PORT }}:80"
    networks:
      default:
        aliases:
          - ui
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    environment:
      KEYCLOAK_URL: "http://{{ SLM_HOSTNAME }}:{{ KEYCLOAK_PORT }}/auth"
      AWX_URL: "http://{{ SLM_HOSTNAME }}:{{ AWX_PORT_HTTP }}"
      BASYX_AAS_GUI_URL: "http://{{ SLM_HOSTNAME }}:3000"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080" ]

  resource-management:
    image: "ghcr.io/eclipse-slm/slm/resource-management:{{ SLM_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://{{ SLM_HOSTNAME }}:{{ KEYCLOAK_PORT }}/auth"
      BASYX_AASREGISTRY_URL: "http://{{ SLM_HOSTNAME }}:4000/registry"
      BASYX_AASSERVER_URL: "http://{{ SLM_HOSTNAME }}:4001/aasServer"
      MONITORING_SERVICE_URL: "http://{{ SLM_HOSTNAME }}:{{ MONITORING_SERVICE_PORT }}"
      SERVER_MAXHTTPHEADERSIZE: 100KB
      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: "{{ SLM_IP }}"
    ports:
      - "{{ RESOURCE_MANAGEMENT_PORT }}:9010"
    networks:
      default:
        aliases:
          - resource-management
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9010/swagger-ui/index.html" ]

  resource-management-database:
    image: "ghcr.io/eclipse-slm/mariadb:{{ RESOURCE_MANAGEMENT_DATABASE_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ RESOURCE_MANAGEMENT_DATABASE_PORT }}:3306"
    networks:
      default:
        aliases:
          - resource-management-database
    environment:
      MARIADB_ROOT_PASSWORD: "{{ database_user_passwords.resource_management.root_password }}"
      MARIADB_USER: "{{ database_user_passwords.resource_management.username }}"
      MARIADB_PASSWORD: "{{ database_user_passwords.resource_management.password }}"
      MARIADB_DATABASE: resources
      KEYCLOAK_AUTHSERVERURL: "http://{{ SLM_HOSTNAME }}:{{ KEYCLOAK_PORT }}/auth"
    volumes:
      - resource-management-database_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  resource-management-init:
    image: "ghcr.io/eclipse-slm/slm/resource-management-init:{{ SLM_VERSION }}"
    restart: "no"
    depends_on:
      - resource-management
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://{{ SLM_HOSTNAME }}:{{ KEYCLOAK_PORT }}/auth"
      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: "{{ SLM_IP }}"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"

  service-management:
    image: "ghcr.io/eclipse-slm/slm/service-management:{{ SLM_VERSION }}"
    restart: unless-stopped
    depends_on:
      - service-management-database
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://{{ SLM_HOSTNAME }}:{{ KEYCLOAK_PORT }}/auth"
      GIT_SERVICEOFFERINGIMPORTER_UPDATERINTERVALMINUTES: "{{ SERVICE_MANAGEMENT_GIT_CHECK_INTERVAL_MINUTES }}"
      BASYX_AASREGISTRY_URL: "http://{{ SLM_HOSTNAME }}:4000/registry"
      BASYX_AASSERVER_URL: "http://{{ SLM_HOSTNAME }}:4001/aasServer"
      SERVICEMANAGEMENT_URL: "http://{{ SLM_HOSTNAME }}:{{ SERVICE_MANAGEMENT_PORT }}"
      SERVER_MAXHTTPHEADERSIZE: 100KB
      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: "{{ SLM_IP }}"
    ports:
      - "{{ SERVICE_MANAGEMENT_PORT }}:9020"
    networks:
      default:
        aliases:
          - service-management
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9020/swagger-ui/index.html" ]

  service-management-init:
    image: "ghcr.io/eclipse-slm/slm/service-management-init:{{ SLM_VERSION }}"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    environment:
      SERVICEMANAGEMENT_INITDIRECTORIES: "{{ SERVICE_MANAGEMENT_INITIALIZATION_LOCAL_DIRECTORIES }}"
      SERVICEMANAGEMENT_GITREPOS_URLS: "{{ SERVICE_MANAGEMENT_INITIALIZATION_GIT_REPOS }}"

  service-management-database:
    image: "ghcr.io/eclipse-slm/mariadb:{{ SERVICE_MANAGEMENT_DATABASE_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ SERVICE_MANAGEMENT_DATABASE_PORT }}:3306"
    networks:
      default:
        aliases:
          - service-management-database
    environment:
      MARIADB_ROOT_PASSWORD: "{{ database_user_passwords.service_management.root_password }}"
      MARIADB_USER: "{{ database_user_passwords.service_management.username }}"
      MARIADB_PASSWORD: "{{ database_user_passwords.service_management.password }}"
      MARIADB_DATABASE: services
    volumes:
      - service-management-database_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  notification-service:
    image: "ghcr.io/eclipse-slm/slm/notification-service:{{ SLM_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ NOTIFICATION_SERVICE_PORT }}:9001"
    environment:
      KEYCLOAK_AUTHSERVERURL: "http://{{ SLM_HOSTNAME }}:{{ KEYCLOAK_PORT }}/auth"
      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: "{{ SLM_IP }}"
    networks:
      default:
        aliases:
          - notification-service
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9001/swagger-ui/index.html" ]

  notification-service-database:
    image: "ghcr.io/eclipse-slm/mariadb:{{ NOTIFICATION_SERVICE_DATABASE_VERSION }}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "{{ LOGGING_MAX_FILE }}"
        max-size: "{{ LOGGING_MAX_SIZE }}"
    ports:
      - "{{ NOTIFICATION_SERVICE_DATABASE_PORT }}:3306"
    networks:
      default:
        aliases:
          - notification-service-database
    environment:
      MARIADB_ROOT_PASSWORD: "{{ database_user_passwords.notification_service.root_password }}"
      MARIADB_USER: "{{ database_user_passwords.notification_service.username }}"
      MARIADB_PASSWORD: "{{ database_user_passwords.notification_service.password }}"
      MARIADB_DATABASE: notifications
    volumes:
      - notification-service-database_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

networks:
  default:

volumes:
  notification-service-database_data:
  resource-management-database_data:
  service-management-database_data:
