apiVersion: v1
kind: Service
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  type: ClusterIP
  selector:
    app: monitoring
  ports:
    - name: monitoring-prometheus-aas
      protocol: TCP
      port: {{.Values.monitoring.service_port}}
      targetPort: 8080
    - name: prometheus
      protocol: TCP
      port: {{.Values.prometheus.port}}
      targetPort: 9090
