- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_access_token is defined) and (keycloak_access_token|length > 0)
      - (keycloak_clients is defined) and (keycloak_clients|length > 0)

- include_role:
    name: "keycloak/keycloak_client"
    tasks_from: clients/get_oidc-keycloak-json.yml

- name: Store Keycloak client config in Consul
  community.general.consul_kv:
    host: ipa-wn1152
    port: 8500
    token: "{{ consul_token }}"
    key: "config/{{ client_id }}/keycloak"
    value: "{{ keycloak_oidc_json }}"
