- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_realm is defined) and (keycloak_realm|length > 0)
      - (keycloak_access_token is defined) and (keycloak_access_token|length > 0)
      - (keycloak_clients is defined) and (keycloak_clients|length > 0)

- include_role:
    name: "keycloak/keycloak_init"
    tasks_from: store_client_config.yml
  loop: "{{ keycloak_clients }}"
  vars:
    client_id: "{{ item.client_id }}"
