- name: "Consul Init | Assert variables"
  assert:
    that:
      - (consul_url is defined) and (consul_url|length > 0)
      - (consul_token is defined) and (consul_token|length > 0)
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)

- name: "Consul Init | Wait for Keycloak being up"
  uri:
    url: "{{ keycloak_auth_url }}/realms/fabos/.well-known/openid-configuration"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 120
  delay: 3

- name: "Consul Init | Create auth method for Keycloak"
  uri:
    url: "{{ consul_url }}/v1/acl/auth-method"
    method: PUT
    headers:
      authorization: "Bearer {{ consul_token }}"
    body_format: json
    body:
      Name: keycloak
      Type: jwt
      Description: FabOS Keycloak Instance
      Config:
        OIDCDiscoveryURL: "{{ keycloak_auth_url }}/realms/fabos"
        OIDCDiscoveryCACert: ''
        ClaimMappings:
          given_name: first_name
          family_name: last_name
        ListClaimMappings:
          groups: groups
          "/realm_access/roles": resources
    status_code: 200
  register: output_put_auth_method
