keycloak_clients:
  - client_id: awx_jwt_authenticator
    public_client: false
    service_accounts_enabled: false
  - client_id: ui
    public_client: true
    service_accounts_enabled: false
  - client_id: resource_management
    public_client: false
    service_accounts_enabled: true
  - client_id: service_management
    public_client: false
    service_accounts_enabled: true
  - client_id: notification_service
    public_client: false
    service_accounts_enabled: false

keycloak_realms:
  - realm: "fabos"
    displayName: ""
    displayNameHtml: ""
    enabled: true
    loginTheme: "fabos"
    accessTokenLifespan: 86400

keycloak_realm: fabos

keycloak_realm_roles:
  - name: ssp-user
    isDefault: true
  - name: slm-admin
    isDefault: false

keycloak_default_user:
  username: fabos
  enabled: true
  credentials:
    - type: password
      value: password
      temporary: false
  realmRoles: [ "ssp-user", "slm-admin" ]

keycloak_client_configs_store_directory: "/config/service-management-init"
