### Inputs
- name: "Assert inputs of 'keycloak/client | get_admin_access_token.yml'"
  assert:
    that:
      - (KEYCLOAK_AUTH_URL is defined) and (KEYCLOAK_AUTH_URL|length > 0)               # Auth URL of the Keycloak instance
      - (KEYCLOAK_ADMIN_USERNAME is defined) and (KEYCLOAK_ADMIN_USERNAME|length > 0)   # Username of Keycloak admin
      - (KEYCLOAK_ADMIN_USERNAME is defined) and (KEYCLOAK_ADMIN_USERNAME|length > 0)   # Password of Keycloak admin

- name: "Get Keycloak admin access token"
  uri:
    url: "{{ KEYCLOAK_AUTH_URL }}/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ KEYCLOAK_ADMIN_USERNAME }}"
      password: "{{ KEYCLOAK_ADMIN_PASSWORD }}"
      grant_type: "password"
      client_id: "admin-cli"
    status_code: 200
    validate_certs: no
  register: output_keycloak_login

### Outputs
- set_fact:
    keycloak_access_token: "{{ output_keycloak_login.json.access_token }}"    # Keycloak access token for admin user

