- set_fact:
    vault_url: "{{ lookup('env', 'VAULT_URL') }}"                       # URL of Vault instance which should be initialized
    vault_token: "{{ vault_root_token }}"

- debug:
    msg: "{{ vault_token }}"

- name: "Create app role Auth Method 'approle'"
  include_tasks: actions/create_approle_auth_method.yml

- name: "Create AppRoles"
  include_tasks: actions/init_approle.yml
  vars:
    approle_name: "{{ approle.name }}"
    approle_policies: "{{ approle.policies }}"
  loop: "{{ vault_approles }}"
  loop_control:
    loop_var: approle

- name: "Create secret engines"
  include_tasks: actions/create_kv_secret_engine.yml
  vars:
    kv_secret_engine_name: "{{ item }}"
  with_items: "{{ vault_kv_secret_engines }}"

- name: "Wait for Keycloak being up"
  uri:
    url: "{{ keycloak_auth_url }}/realms/{{ KEYCLOAK_REALM }}/.well-known/openid-configuration"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 120
  delay: 3

- name: "Configure JWT auth via Keycloak"
  include_tasks: actions/configure_keycloak_jwt_auth_method.yml
  vars:
    mount_auth_path: "jwt"
    oidc_discovery_url: "{{ keycloak_auth_url }}/realms/{{ KEYCLOAK_REALM }}"
