service-management:
  url: http://{{ service_management_host }}:{{ service_management_port }}
  init-directories: init-public/,init-private/
  git-repos:
    urls: "https://github.com/FabOS-AI/fabos-slm-service-management-content.git"
    clone-directory: tmp/

keycloak:
  auth-server-url: {{ keycloak_auth_server_url }}
  realm: fabos
  username: fabos
  password: password
