version: '3'

services:

  slm-installer:
    build: .
    image: ghcr.io/eclipse-slm/slm/uninstaller:1.4.0-SNAPSHOT
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      - "./env.yml:/env/env.yml"
      - "./src:/src"
      - "./result_compose:/compose"
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
