- name: "Check if Keycloak OIDC configuration file '{{ keycloak_oidc_file }}' exists"
  stat:
    path: "{{ keycloak_oidc_file }}"
  register: stat_result
  until:
    - stat_result.stat.exists
  retries: 1000
  delay: 1

- name: "Read Keycloak token from file '{{ keycloak_oidc_file }}'"
  include_vars:
    file: "{{keycloak_oidc_file}}"
    name: keycloak_oidc_json

- set_fact:
    keycloak_oidc_settings: ""
    new_oidc: ""


- name: "Create OIDC JSON Object"
  set_fact:
    keycloak_oidc_settings: "{{ lookup('file', keycloak_oidc_file) | from_json }}"

- name: "Create OIDC Settings"
  set_fact:
    new_oidc: "{{ lookup('template', 'oidc_settings.json.j2') }}"

- assert:
    that:
      - (keycloak_oidc_settings is defined) and (keycloak_oidc_settings|length > 0)
    fail_msg: "Import of Keycloak OIDC settings from file '{{ keycloak_oidc_file }}' failed"
