version: '3'

services:
  monitoring-prometheus-aas:
    image: "fabos4ai/fabos-monitoring-prometheus-aas:{{ MONITORING_SERVICE_VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - monitoring
    ports:
      - "{{ MONITORING_SERVICE_PORT }}:8080"

  monitoring-prometheus-configurator:
    image: fabos4ai/fabos-monitoring-prometheus-configurator:0.0.1-SNAPSHOT
    restart: unless-stopped
    networks:
      default:
        aliases:
          - monitoring-prometheus-configurator
    ports:
      - "{{ MONITORING_CONFIGURATOR_PORT }}:5000"
    volumes:
      - prometheus-targets:/code/targets

  prometheus:
    image: "ghcr.io/eclipse-slm/monitoring-prometheus:{{ SLM_VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - prometheus
    ports:
      - "{{ PROMETHEUS_PORT }}:9090"
    volumes:
      - prometheus-targets:/etc/prometheus/targets/
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit
      interval: 60s
      retries: 5
      timeout: 10s

volumes:
  prometheus-targets:
