version: '3'

services:
  monitoring-prometheus-aas:
    image: "fabos4ai/fabos-monitoring-prometheus-aas:{{ MONITORING_SERVICE_VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - monitoring
    ports:
      - "{{ MONITORING_SERVICE_PORT }}:8080"

  prometheus:
    image: "ghcr.io/eclipse-slm/monitoring-prometheus:{{ SLM_VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - prometheus
    ports:
      - "{{ PROMETHEUS_PORT }}:9090"
    volumes:
      - config-prometheus:/etc/prometheus/
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit
      interval: 60s
      retries: 5
      timeout: 10s

volumes:
  config-prometheus:
