version: '3'

services:
  monitoring-prometheus-aas:
    image: "ghcr.io/eclipse-slm/slm-monitoring-prometheus-aas:{{ MONITORING_PROMETHEUS_AAS_VERSION }}"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - monitoring
    ports:
      - "{{ MONITORING_PROMETHEUS_AAS_PORT }}:8080"

  prometheus:
    image: "ghcr.io/eclipse-slm/monitoring-prometheus:{{ PROMETHEUS_VERSION }}"
    restart: unless-stopped
    environment:
      CONSUL_URL: "{{ CONSUL_URL }}"
      CONSUL_TOKEN: "{{ _consul_token }}"
    networks:
      default:
        aliases:
          - prometheus
    extra_hosts:
      - "{{ SLM_HOSTNAME }}:172.17.0.1"
    ports:
      - "{{ PROMETHEUS_PORT }}:9090"
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit
      interval: 60s
      retries: 5
      timeout: 10s
