version: '3'

services:
  aas-registry:
    image: eclipsebasyx/aas-registry:1.4.0
    restart: unless-stopped
    depends_on:
      - aas-database
      - aas-server
      - aas-gui
      - aas-broker
    networks:
      default:
        aliases:
          - aas-registry
    ports:
      - "4000:4000"
    environment:
      basyxregistry_registry_events: MQTTV2_SIMPLE_ENCODING
      basyxmqtt_server: tcp://aas-broker:1883
      basyxregistry_registry_backend: MongoDB
      basyxmongodb_dbconnectionstring: mongodb://aas-database:27017/
      basyxcontext_accesscontrolalloworigin: "*"
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  aas-server:
    image: eclipsebasyx/aas-server:1.4.0
    restart: unless-stopped
    depends_on:
      - aas-database
      - aas-broker
    networks:
      default:
        aliases:
          - aas-server
    ports:
      - "4001:4001"
    environment:
      basyxaas_registry_path: http://aas-registry:4000/registry/api/v1/registry
      basyxaas_aas_events: MQTTV2_SIMPLE_ENCODING
      basyxaas_aas_backend: MongoDB
      basyxaas_aas_aasxupload: Enabled
      basyxaas_registry_host: http://${SLM_HOSTNAME}:4001/aasServer
      basyxmongodb_dbconnectionstring: mongodb://aas-database:27017/
      basyxmqtt_server: tcp://aas-broker:1883
      basyxcontext_accesscontrolalloworigin: "*"
      waiting_for: '[{"host":"aas-registry","port":"4000"}]'
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  aas-database:
    image: mongo:latest
    restart: unless-stopped
    networks:
      default:
        aliases:
          - aas-database
    volumes:
      - "aas_database:/data/db"

  aas-gui:
    image: eclipsebasyx/aas-gui:v230703
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_REGISTRY_PATH: "http://${SLM_HOSTNAME}:4000/registry"
      VITE_AAS_SERVER_PATH: "http://${SLM_HOSTNAME}:4001/aasServer"
      VITE_PRIMARY_COLOR: "00A0E3"
    volumes:
      - "./config/aas-gui/logo:/app/src/assets/Logo"

  aas-broker:
    image: ghcr.io/fabos-ai/aas-transformer/aas-broker:${AAS_TRANSFORMER_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "1883:1883"
      - "1801:9001"
    networks:
      default:
        aliases:
          - aas-broker

  aas-transformer:
    image: ghcr.io/fabos-ai/aas-transformer/service:${AAS_TRANSFORMER_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    depends_on:
      - aas-transformer-database
    ports:
      - "4010:4010"
    networks:
      default:
        aliases:
          - aas-transformer
    environment:
      DATABASE_HOST: aas-transformer-database
      DATABASE_SCHEMA: ${AAS_TRANSFORMER_DATABASE_NAME}
      DATABASE_USERNAME: ${AAS_TRANSFORMER_DATABASE_USER}
      DATABASE_PASSWORD: ${AAS_TRANSFORMER_DATABASE_PASSWORD}
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"

  aas-transformer-database:
    image: mariadb:10.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    networks:
      default:
        aliases:
          - aas-transformer-database
    environment:
      MARIADB_USER: ${AAS_TRANSFORMER_DATABASE_USER}
      MARIADB_PASSWORD: ${AAS_TRANSFORMER_DATABASE_PASSWORD}
      MARIADB_DATABASE: ${AAS_TRANSFORMER_DATABASE_NAME}
      MARIADB_ROOT_PASSWORD: ${AAS_TRANSFORMER_DATABASE_ROOT_PASSWORD}
    volumes:
      - "aas_transformer_database:/var/lib/mysql"

  aas-transformer-initializer:
    image: ghcr.io/fabos-ai/aas-transformer/initializer:${AAS_TRANSFORMER_VERSION}
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}

volumes:
  aas_database:
  aas_transformer_database:
