- name: "Uninstall SLM"
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    compose_project_name: eclipse-slm
  tasks:
    - name: "Stop containers"
      ansible.builtin.shell: "docker stop $(docker ps -q -f label=com.docker.compose.project={{ compose_project_name }})"
      ignore_errors: true
    - name: "Remove containers"
      ansible.builtin.shell: "docker rm --volumes $(docker ps -a -q -f label=com.docker.compose.project=eclipse-slm)"
    - name: "Remove volumes"
      ansible.builtin.shell: "docker volume rm $(docker volume ls -q -f label=com.docker.compose.project=eclipse-slm)"
    - name: "Remove networks"
      ansible.builtin.shell: "docker network rm {{ compose_project_name }}_default"
