awx_config:
  admin:
    username: admin
    password: 'password'
  jwt_authenticator:
    username: awx_jwt_authenticator
    password: ''
  consul:
    token:

keycloak_config:
  hostname: localhost
  admin:
    username: admin
    password: ''
  database:
    host: keycloak-database
    url_host: keycloak-database
    schema: keycloak
    username: keycloak
    password: ''
  http:
    relative_path: /auth

consul_config:
    {
      "datacenter": "fabos",
      "domain": ".consul",
      "bind_addr": "0.0.0.0",
      "retry_join": [ "0.0.0.0" ],
      "retry_interval": "30s",
      "retry_max": 0,
      "encrypt": "PDfibAdpofFo2mpIvwwQEtuo5+Z7RmMR9CLGvBWSjK0=",
      "verify_incoming": false,
      "verify_outgoing": false,
      "verify_server_hostname": false,
      "ui_config": {
        "enabled": true
      },
      "acl": {
        "enabled": true,
        "default_policy": "deny",
        "down_policy": "extend-cache",
        "enable_token_persistence": true,
        "enable_token_replication": true,
        "tokens": {
          "master": "dummy_token"
        }
      }
    }

