name: Build Core

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MAVEN_CLI_OPTS: "-T 8 -s ci/ci_maven_settings.xml --batch-mode --errors --fail-at-end --show-version --no-transfer-progress -DinstallAtEnd=true -DdeployAtEnd=true"
      MAVEN_PROFILES: ""
    strategy:
      matrix:
        build: [
          {
            type: "frontend",
            maven-projects: "ui"
          },
          {
            type: "backend",
            maven-projects: "!ui"
          }
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          path: ci/ci_maven_settings.xml
          githubServer: false
          servers: '[
            {
              "id": "ghcr.io",
              "username": "${{github.actor}}",
              "password": "${{secrets.GITHUB_TOKEN}}"
            }
          ]'
      - name: Build '${{ matrix.build.type }}' with Maven
        run: mvn $MAVEN_PROFILES $MAVEN_CLI_OPTS --projects '${{ matrix.build.maven-projects }}' deploy
      - name: Log test output on failure
        if: failure() || cancelled()
        run: find . -type f -path "*test-reports/*-output.txt" -exec tail -n +1 {} +
