name: Deploy Staging Environment


on:
  push:
    branches:
      - main
      - develop
      - release-*
#  workflow_run:
#    workflows: Build Core
#    branches:
#      - main
#      - release/*
#      - develop
#    types: completed

env:
  STAGING_VM_IP: ${{ github.ref_name == 'develop' && '10.3.7.166' || '10.3.7.145' }}
  STAGING_VM_HOSTNAME: ${{ github.ref_name == 'develop' && 'develop.stage.slm.vfk' || 'main.stage.slm.vfk' }}

jobs:
  deploy-staging-environment:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.STAGING_VM_IP}}
          username: vfk
          key: ${{secrets.RUNNER_PRIVATE_KEY}}
          envs: STAGING_VM_HOSTNAME
          script: |
            echo ${{github.ref_name}}
            cd /staging/tmp/stack/compose || true
            docker-compose down --volumes || true
            docker system prune -f
            cd /staging && rm -r tmp && mkdir tmp && cd tmp
            git clone -b ${{github.ref_name}} https://github.com/${{github.repository}}.git
            cd slm
            CORE_VERSION=$(cat pom.xml | grep -oPm1 "(?<=<revision>)[^<]+")
            cd stack/compose
            sed -ir "s/^[#]*\s*SLM_HOSTNAME=.*/SLM_HOSTNAME=$STAGING_VM_HOSTNAME/" .env
            sed -ir "s/^[#]*\s*SLM_VERSION=.*/SLM_VERSION=$CORE_VERSION/" .env
            echo ${{secrets.GITHUB_TOKEN}} | docker login -u${{github.actor}} --password-stdin ghcr.io
            docker-compose pull
            docker-compose up -d --force-recreate
